# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions


name: Build and deploy Python app to Azure Web App - app-backend-usgunhunum63q

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-backend-usgunhunum63q
  WORKING_DIRECTORY: '.'        # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.10'        # set the version to use
  STARTUP_COMMAND: ''           # set this to the startup command required to start the gunicorn server. default it is empty

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout front-end
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./frontend

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: ./backend

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      # compress

      - name: Zip artifect for deployment
        run: zip release.zip -r ./* --exclude *venv/*
        working-directory: ./backend


      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: ./backend/release.zip


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job (consolidated)
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: unzip artifact for deployment
        run: unzip release.zip

      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}
  
      - name: App SErvice Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}
          slot-name: 'Production'

      - name: Azure Logout
        run: |
          az logout
